<?php

namespace Puzzle\AppBundle\Repository;

/**
 * VisitCounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitCounterRepository extends \Doctrine\ORM\EntityRepository
{
}
